services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_recorder_test
    container_name: postgres_book_recorder_test
    ports:
      - '5434:5432'
